In [1]:
import numpy as np
ar = np.arrange(2,51,3)
print(ar)

AttributeError: module 'numpy' has no attribute 'arrange'

In [2]:
import numpy as np
a1=[]
a2=[]
for i in range (0,5):
    ele = int(input())
    a1.append(ele)
for i in range (0,5):
    ele = int(input())
    a2.append(ele)
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))

5
9
5
5
5
5
5



ValueError: invalid literal for int() with base 10: ''

In [2]:
import numpy as np
arr = np.array([[1,2,3],[1,3,5],[1,3,4]])
print(arr.ndim)
print(arr.size)

2
9


In [3]:
import numpy as np
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)

1
2


In [5]:
import numpy as np
arr1= np.random.rand(3,3)
arr2= np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print()
print(np.hstack((arr1,arr2)))

[[0.37415055 0.79343631 0.47637674]
 [0.73443097 0.21957783 0.77424673]
 [0.21946348 0.72892888 0.34584663]
 [0.57863956 0.66843946 0.23101995]
 [0.54466749 0.33887246 0.83117823]
 [0.58133573 0.70799486 0.39391231]]

[[0.37415055 0.79343631 0.47637674 0.57863956 0.66843946 0.23101995]
 [0.73443097 0.21957783 0.77424673 0.54466749 0.33887246 0.83117823]
 [0.21946348 0.72892888 0.34584663 0.58133573 0.70799486 0.39391231]]


In [6]:
import numpy as np
arr= np.array([1,9,3,1,5,2,5,6,4,3,9,7,6,8,9,2,6,7,8])
print(np.unique(arr,return_counts= True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 1, 2, 3, 2, 2, 3], dtype=int64))
